version: '3.8'

services:
  python_bot:
    build: ./python_bot
    container_name: psb_python_bot
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ${NAS_PATH}:${NAS_PATH}
    networks:
      - bot_network

  baileys_bot:
    build: ./baileys_bot
    container_name: psb_baileys_bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WA_API_TOKEN=${WA_API_TOKEN}
      # Ini wajib ada agar Baileys melapor ke port 5555 Python
      - WEBHOOK_URL=http://psb_python_bot:5555/webhook 
    networks:
      - bot_network

  baileys_pelanggan:
    build: ./baileys_pelanggan
    container_name: psb_baileys_pelanggan
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - WA_API_TOKEN=${WA_API_TOKEN}
      # Sengaja KOSONG, Bot Pelanggan hanya untuk kirim notifikasi 1 arah
      - WEBHOOK_URL= 
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
